// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ98mcHM6zsxTRCrl1oSnI9QujEwzpj_A',
    appId: '1:710204569126:web:aa1a8a3fa476945e6058e7',
    messagingSenderId: '710204569126',
    projectId: 'loginapp-a3fd3',
    authDomain: 'loginapp-a3fd3.firebaseapp.com',
    storageBucket: 'loginapp-a3fd3.appspot.com',
    measurementId: 'G-MQC91L4N2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6bDSnwycTXhAOIIX7-xPmo4-tO99vHlA',
    appId: '1:710204569126:android:9ade17c8c184f5f06058e7',
    messagingSenderId: '710204569126',
    projectId: 'loginapp-a3fd3',
    storageBucket: 'loginapp-a3fd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXF2RJonYSQCr-QDXaORw3irytNwmq1kw',
    appId: '1:710204569126:ios:37fd3e851e0e4b4b6058e7',
    messagingSenderId: '710204569126',
    projectId: 'loginapp-a3fd3',
    storageBucket: 'loginapp-a3fd3.appspot.com',
    androidClientId: '710204569126-4b8ibom5kpvlth806vg5spk7s47pf97d.apps.googleusercontent.com',
    iosClientId: '710204569126-v3bik3ooc2i3qr1m5q3vci2n3r3egghc.apps.googleusercontent.com',
    iosBundleId: 'com.example1.loginTrail1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ98mcHM6zsxTRCrl1oSnI9QujEwzpj_A',
    appId: '1:710204569126:web:bfafc705cc526c7e6058e7',
    messagingSenderId: '710204569126',
    projectId: 'loginapp-a3fd3',
    authDomain: 'loginapp-a3fd3.firebaseapp.com',
    storageBucket: 'loginapp-a3fd3.appspot.com',
    measurementId: 'G-C0BJNNWQLQ',
  );

}